package protocol;

public enum ErrorType {
    SERVER_CLOSED,
    INVALID_GAME_SIZE,
    INVALID_SESSION_CODE,
    INVALID_PLACEMENT,
    INVALID_SECRET,
    NO_GAME_IN_PROGRESS,
    INVALID_PLAYER,
    ALREADY_IN_QUEUE,
    NOT_IN_QUEUE
}
