name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Setze JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Kompiliere Server und Client
        run: |
          mkdir -p bin
          javac -d bin src/server/Server.java src/client/Client.java

      - name: Starte Server im Hintergrund
        run: |
          java -cp bin server.Server &
          echo $! > server_pid.txt
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}

      - name: Warte auf Server-Start
        run: |
          for i in {1..10}; do
            if grep -q "Server gestartet" <(tail -n 10 server.log); then
              echo "Server erfolgreich gestartet."
              exit 0
            fi
            sleep 2
          done
          echo "Serverstart fehlgeschlagen."
          exit 1

      - name: Führe Client-Tests aus
        run: java -cp bin client.ClientTest

      - name: Beende Server
        run: |
          kill $(cat server_pid.txt)
          rm server_pid.txt